# This is the configure file to my personal pages
#

# Site settings
title: Ruyuan Zhang
owner:
  name: Ruyuan Zhang
  email: ruyuanzhangATgmailDOTcom
description: > # this means to ignore newlines until "baseurl:"
  Here is the Ruyuan Zhang's personal webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ruyuanzhang.github.io" # the base hostname & protocol for your site
twitter_username: ruyuanzhang
github_username:  ruyuanzhang
permalink: pretty




exclude: ['README.md']


# Build settings
markdown: kramdown
port: 3000 # change server port to 3000,since 4000 is conflict with nomachine

